[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"

[functions."refresh-token"]
  schedule = "@daily"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
